use_frameworks!

platform :ios, '9.0'

target 'degpeg-b2c-sdk-ios_Example' do
  pod 'degpeg-b2c-sdk-ios', :path => '../'

  target 'degpeg-b2c-sdk-ios_Tests' do
    inherit! :search_paths

    
  end
end
